accessibility: protected
containerPort: 5000
ports:
- containerPort: 443
  name: https
  protocol: TCP

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 1
  periodSeconds: 5

livenessProbe:
  httpGet:
    path: /
    port: 5000
  periodSeconds: 5
