accessibility: protected
ports:
  - containerPort: 5000
    name: http0
  - containerPort: 5001
    name: http1
  - containerPort: 5002
    name: http2
command:
  - sh
  - -cxe
  - PORT=5000 /go/bin/echo &\\ PORT=5001 /go/bin/echo\\ PORT=5002 /go/bin/echo
