accessibility: protected
ports:
  - containerPort: 5000
    name: http0
  - containerPort: 5001
    name: http1
  - containerPort: 5002
    name: http2
protocol: TCP
command:
  - sh
  - -cxe
  - env PORT=5000 /go/bin/echo &\env PORT=5001 /go/bin/echo &\env PORT=5002 /go/bin/echo
