accessibility: private
ports:
  - containerPort: 5000
  - containerPort: 5001
  - containerPort: 5002
command:
  - sh
  - -cxe
  - PORT=5000 /go/bin/echo &; PORT=5001 /go/bin/echo; PORT=5002 /go/bin/echo
